src/routes/articles.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_paginate import Pagination, get_page_parameter
from src.logic import articles
from datetime import datetime
import os

# Create a Blueprint instance for the search routes
blueprint_article = Blueprint('articles', __name__)

@blueprint_article.context_processor
def inject_articles_functions():
    return dict(load_article=articles.load_article, parse_menu_content = articles.parse_menu_content)

@blueprint_article.route('/')
def index():
    try:
        homepage_article = articles.load_article("_sp_Homepage")
        menu_article = articles.load_article('_sp_Menu')
        latest_version = menu_article['versions'][-1]
        menu_content = latest_version['content']
        parsed_menu = articles.parse_menu_content(menu_content)
        print(menu_content)
        return render_template('special_page.html', article=homepage_article)
    except:
        return render_template('index.html')
    
@blueprint_article.route('/about')
def about():
    try:
        about = articles.load_article("_sp_About")
        return render_template('special_page.html', article=about)
    except:
        return render_template('index.html')


@blueprint_article.route('/article/<filename>')
def view_article(filename):
    try:
        articleFile = articles.load_article(filename)
    except FileNotFoundError:
        return "Article not found", 404
    
    if articleFile:
        return render_template('article.html', article=articleFile)
    else:
        return render_template('article.html', article=None)
    
@blueprint_article.route('/article/<filename>/versions')
def view_article_versions(filename):
    article = articles.load_article(filename)
    return render_template('article_versions.html', article=article)

@blueprint_article.route('/article/<filename>/compare_versions', methods=['POST'])
def compare_versions(filename):
    selected_versions = request.form.getlist('selected_versions')

    if len(selected_versions) != 2:
        return "Please select exactly two versions to compare.", 400

    article_data = articles.load_article(filename)
    version1 = next((v for v in article_data['versions'] if v['timestamp'] == selected_versions[0]), None)
    version2 = next((v for v in article_data['versions'] if v['timestamp'] == selected_versions[1]), None)

    if not version1 or not version2:
        return "Selected versions not found.", 404

    return render_template('compare_versions.html', article_data=article_data, version1=version1, version2=version2, render_diff=articles.render_diff)

@blueprint_article.route('/article/<filename>/restore/<timestamp>')
def restore_version(filename, timestamp):
    article_data = articles.load_article(filename)
    version = next((v for v in article_data['versions'] if v['timestamp'] == timestamp), None)

    if version:
        version['timestamp'] = datetime.now().isoformat()
        article_data['versions'].append(version)  # Replace versions with the selected version
        articles.save_article_data(filename, article_data)
        return redirect(url_for('articles.view_article', filename=filename))
    else:
        return "Version not found", 404


@blueprint_article.route('/article/<filename>/version/<timestamp>')
def view_specific_version(filename, timestamp):
    article_data = articles.load_article(filename)
    version = next((v for v in article_data['versions'] if v['timestamp'] == timestamp), None)
    if version:
        return render_template('view_specific_version.html', article_data=article_data, version=version)
    else:
        return "Version not found", 404

@blueprint_article.route('/new', methods=['GET', 'POST'])
def new_article():
    return articles.create_or_edit_article(None)

@blueprint_article.route('/edit/<filename>', methods=['GET', 'POST'])
def edit_article(filename):
    return articles.create_or_edit_article(filename)

@blueprint_article.route('/tag/<tag>')
def tagged_articles(tag):
    page = request.args.get(get_page_parameter(), type=int, default=1)
    articles_per_page = 10  # Adjust as needed

    # Get a list of articles with the specified tag
    tagged_articles = articles.get_tagged_articles(tag)

    # Paginate the tagged articles
    pagination = Pagination(page=page, total=len(tagged_articles), per_page=articles_per_page, css_framework='bootstrap4')
    articles_to_display = tagged_articles[(page - 1) * articles_per_page:page * articles_per_page]

    return render_template('tagged_articles.html', tag=tag, articles=articles_to_display, pagination=pagination)

@blueprint_article.route('/article/<filename>/delete/<timestamp>')
def delete_version(filename, timestamp):
    article = articles.load_article(filename)
    version = next((v for v in article.versions if v['timestamp'] == timestamp), None)
    if version:
        article.versions.remove(version)
        articles.save_article_data(filename, article)
        return redirect(url_for('view_article_versions', filename=filename))
    else:
        return "Version not found", 404
    
@blueprint_article.route('/manage_articles', methods=['GET', 'POST'])
def manage_articles():
    page = request.args.get('page', type=int, default=1)
    articles_per_page = 10  # Adjust as needed
    articles_list = articles.get_article_list()
    pagination = Pagination(page=page, total=len(articles_list), per_page=articles_per_page, css_framework='bootstrap4')
    articles_to_display = articles_list[(page-1)*articles_per_page:page*articles_per_page]
    print(articles_list)
    return render_template('manage_articles.html', articles=articles_to_display, pagination=pagination)

@blueprint_article.route('/confirm_delete/<filename>')
def confirm_delete(filename):
    article_data = articles.load_article(filename)  
    return render_template('confirm_delete.html', article=article_data)

@blueprint_article.route('/delete_article/<filename>', methods=['GET', 'POST'])
def delete_article(filename):
    article_data = articles.load_article(filename)
    if article_data:
        os.remove(os.path.join('content', filename + '.json'))
    return redirect(url_for('manage_articles'))


@blueprint_article.route('/perform_bulk_action', methods=['POST'])
def perform_bulk_action():
    if request.method == 'POST':
        bulk_action = request.form.get('bulk_action')
        selected_articles = request.form.getlist('selected_articles')

        if bulk_action == 'delete':
            for filename in selected_articles:
                article_data = articles.load_article(filename)
                if article_data:
                    os.remove(os.path.join('content', filename + '.json'))

    return redirect(url_for('articles.manage_articles'))

src/routes/search.py
from flask import Blueprint, render_template, request
from flask_paginate import Pagination, get_page_parameter
from src.logic import search as search_logic

# Create a Blueprint instance for the search routes
blueprint_search = Blueprint('search', __name__)

@blueprint_search.route('/search')
def search():
    query = request.args.get('query', '').strip()
    page = request.args.get(get_page_parameter(), type=int, default=1)

    if query:
        search_results = search_logic.search_articles(query)
    else:
        search_results = []

    per_page = 10  # Adjust as needed
    total_results = len(search_results)
    pagination = Pagination(page=page, total=total_results, per_page=per_page, css_framework='bootstrap4')

    start_idx = (page - 1) * per_page
    end_idx = start_idx + per_page
    paginated_results = search_results[start_idx:end_idx]

    return render_template('search_results.html', query=query, results=paginated_results, pagination=pagination)

templates/article.html
{% extends 'base.html' %}

{% block title %}
    {{ article.versions[-1].title }}
{% endblock %}

{% block content %}
    <div class="float_right">
        <a href="{{ url_for('articles.view_article_versions', filename=article.filename) }}" class="btn btn-outline-secondary">View Versions</a>
        <a href="{{ url_for('articles.edit_article', filename=article.filename) }}" class="btn btn-outline-primary ml-2">Edit Article</a>
    </div>
    
    <div class='markdown-body'><h1><strong>{{ article.versions[-1].title }}</strong></h1></div>
    <span class="article-date"><em>Last change: {{ article.versions[-1].timestamp | format_timestamp }}</em></span><br style="clear: both" />

    {% if article.versions[-1].tags %}
        <div class="tags">
            {% for tag in article.versions[-1].tags %}
                {% if tag != "" %}
                    <a href="{{ url_for('articles.tagged_articles', tag=tag) }}"  class="btn btn-info btn-sm p-1">{{ tag }}</a>
                {% endif %}
            {% endfor %}
        </div><br />
    {% endif %}
    
    <div class="article-content markdown-body">
        {{ article.versions[-1].content|markdown_to_html|link_articles|render_blocks|safe }}
    </div>
{% endblock %}

templates/article_versions.html
{% extends 'base.html' %}

{% block title %}
    {{ article.versions[-1].title }} - Versions
{% endblock %}

{% block content %}
    <h1 class="mb-4">{{ article.versions[-1].title }} - Versions</h1>
    <div class="table-responsive">
        <form method="post" action="{{ url_for('articles.compare_versions', filename=article.filename) }}">
            <table class="table table-bordered table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th>Select</th>
                        <th>Version Title</th>
                        <th>Timestamp</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for version in article.versions[::-1] %}
                        <tr>
                            <td>
                                <input type="checkbox" name="selected_versions" value="{{ version.timestamp }}">
                            </td>
                            <td>{{ version.title }}</td>
                            <td>{{ version.timestamp | format_timestamp }}</td>
                            <td>
                                <a href="{{ url_for('articles.view_specific_version', filename=article.filename, timestamp=version.timestamp) }}" class="btn btn-info btn-sm">View</a>
                                <a href="{{ url_for('articles.restore_version', filename=article.filename, timestamp=version.timestamp) }}" class="btn btn-success btn-sm">Restore</a>
                                <a href="{{ url_for('articles.delete_version', filename=article.filename, timestamp=version.timestamp) }}" class="btn btn-danger btn-sm">Delete</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <button type="submit" class="btn btn-primary">Compare Selected Versions</button>
        </form>
    </div>
    <a href="{{ url_for('articles.view_article', filename=article.filename) }}" class="btn btn-primary mt-3">Back to Article</a>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Wiki App{% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.7.0/dist/jquery.min.js"></script>
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='logo.png') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/markdown.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/sidebar.css') }}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
    <link href="https://cdn.jsdelivr.net/npm/jquery.tagify@0.1.0/jquery.tagify.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/jquery.tagify@0.1.0/jquery.tagify.min.js"></script>
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/smoothstate@0.7.2/jquery.smoothState.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/pace-js@latest/pace.min.js"></script>
    
    <link rel="stylesheet" href="{{ url_for('static', filename='js/pace.css') }}">
</head>
<body>
    <div class="d-flex flex-fill navbar-expand-md ">
        <nav id="sidebar" class="flex-fill bg-light navbar-expand-md">
            <div class="sidebar-header">
                <img style="width:40%;;" src="{{ url_for('static', filename='logo.png') }}" /><br />
                <h3><strong>My Wiki</strong></h3>
            </div>
            <div class="search-bar p-3">
                <form class="form-inline" method="get" action="{{ url_for('search.search') }}">
                    <input class="form-control mr-sm-2 w-100" type="search" name="query" id="searchInput" placeholder="Search for articles..." aria-label="Search">
                </form>
            </div>
            <ul class="list-unstyled components p-2">
                {% set menu_article = load_article('_sp_Menu') %}
                {% set latest_version = menu_article['versions'][-1] %}
                {% set menu_content = latest_version['content'] %}
                {% set menu_items = parse_menu_content(menu_content) %}
                {% for item in menu_items %}
                    <li>
                        {% if item.sub_items %}
                            <a href="#submenu_{{ loop.index }}" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">{{ item.title }}</a>
                            <ul class="collapse list-unstyled" id="submenu_{{ loop.index }}">
                                {% for sub_item in item.sub_items %}
                                    <li><a href="{{ sub_item.link }}">{{ sub_item.title }}</a></li>
                                {% endfor %}
                            </ul>
                        {% else %}
                            <a href="{{ item.link }}">{{ item.title }}</a>
                        {% endif %}
                    </li>
                {% endfor %}
            </ul>
        </nav>
        <div class="content flex-fill search-here">
            {% block content %}{% endblock %}
        </div>
    </div>
    <footer class="footer mt-5">
        <p>&copy; <script>document.write( new Date().getFullYear() );</script> Emma de Roo</p>
        <a class="nav-link fnt-10" href="{{ url_for('articles.about') }}">– about this wiki</a>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script>// Initialize previous content and query
        let previousContent = '';
        let previousQuery = '';
        
        // Add an event listener to the search input for real-time searching
        document.getElementById('searchInput').addEventListener('input', function() {
            const query = this.value;
            if (query.trim() === '') {
                // Restore previous content and query when search input is cleared
                window.history.replaceState(null, '', window.location.pathname);
                location.reload();
                return;
            }
            
            // Perform AJAX request to get search results
            $.ajax({
                url: "{{ url_for('search.search') }}",
                data: { query: query },
                success: function(data) {
                    // Update content with search results and store previous content and query
                    previousContent = document.querySelector('.search-here').innerHTML;
                    previousQuery = query;
                    document.querySelector('.search-here').innerHTML = data;
                    
                    // Update URL without full page reload
                    window.history.replaceState(null, '', `?query=${encodeURIComponent(query)}`);
                },
                error: function() {
                    console.error("Error performing search.");
                }
            });
        });</script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <script src="{{ url_for('static', filename='js/smoothstate.js') }}"></script>
        


</body>
</html>

templates/compare_versions.html
{% extends 'base.html' %}

{% block title %}
    Compare Versions - {{ article_data.versions[-1].title }}
{% endblock %}

{% block content %}
    <div class="markdown-body">
        <h2 class="compare-title">Comparing Versions for <em>{{ article_data.versions[-1].title }}</em></h2>
        <div class="version-list">
            <h3 class="mb-3">Versions:</h3>
            <ul class="list-group">
                <li class="list-group-item">
                    <a href="{{ url_for('articles.view_specific_version', filename=article_data.filename, timestamp=version1.timestamp) }}">
                        {{ version1.title }} ({{ version1.timestamp }})
                    </a>
                </li>
                <li class="list-group-item">
                    <a href="{{ url_for('articles.view_specific_version', filename=article_data.filename, timestamp=version2.timestamp) }}">
                        {{ version2.title }} ({{ version2.timestamp }})
                    </a>
                </li>
            </ul>
        </div>

        <h3>Differences:</h3>
        <div class="compare-content">
            <pre class="diff-output">
                {{ render_diff(version2.content, version1.content) | safe }}
            </pre>
        </div>
    </div>
    <a href="{{ url_for('articles.view_article_versions', filename=article_data.filename) }}" class="btn btn-primary mt-3">Back to Versions</a>
{% endblock %}

templates/confirm_delete.html
{% extends 'base.html' %}

{% block title %}
    Confirm Delete
{% endblock %}

{% block content %}
    <h1>Confirm Delete</h1>
    <p>Are you sure you want to delete the article "{{ article.versions[-1].title }}"?</p>
    
    <form method="post" action="{{ url_for('delete_article', filename=article.filename) }}">
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{{ url_for('manage_articles') }}" class="btn btn-secondary">Cancel</a>
    </form>
{% endblock %}

templates/create_edit_article.html
{% extends 'base.html' %}

{% block title %}
    {% if article_data %}
        Edit Article - {{ article_data.versions[-1].title }}
    {% else %}
        Create New Article
    {% endif %}
{% endblock %}

{% block content %}
    <h2>
        {% if article_data %}
            Edit Article - {{ article_data.versions[-1].title }}
            {% if article_data.filename.startswith('_sp_') %}
                <span class="btn btn-warning btn-sm p-1">Special</span>
            {% endif %}
            {% if article_data.filename.startswith('_bl_') %}
                <span class="btn btn-success btn-sm p-1">Block</span>
            {% endif %}
        {% else %}
            Create New Article
        {% endif %}
    </h2><br/>
    <div class="article-content">
        <form method="post" {% if article_data %}action="{{ url_for('articles.edit_article', filename=article_data.filename) }}"{% else %}action="{{ url_for('articles.new_article') }}"{% endif %}>
            <div class="form-group">
                <label for="filename">Filename:</label>
                <input type="text" id="filename" name="filename" class="form-control" {% if article_data %}value="{{ article_data.filename }}"{% endif %} required >
                <input type="hidden" id="filename_old" name="filename_old" class="form-control" {% if article_data %}value="{{ article_data.filename }}"{% endif %}>
            </div>
            <div class="form-group">
                <label for="title">Title:</label>
                <input type="text" id="title" name="title" class="form-control" {% if article_data %}value="{{ article_data.versions[-1].title }}"{% endif %} required>
            </div>
            <div class="form-group">
                <label for="tags">Tags (comma-separated):</label>
                <input type="text" id="tags" name="tags" class="form-control" {% if article_data %}value="{{ ', '.join(article_data.versions[-1].tags) }}"{% endif %}>
            </div>
            <div class="form-group">
                <label for="content">Content:</label>
                <textarea id="content" name="content" class="form-control" rows="8" required>{% if article_data %}{{ article_data.versions[-1].content }}{% endif %}</textarea>
            </div>
            <button type="submit" class="btn btn-primary" id="submit-button">
                {% if article_data %}
                    Save Changes
                {% else %}
                    Create Article
                {% endif %}
            </button>
        </form>
    </div>
    <script>
        const submitButton = document.getElementById("submit-button");
    
        // Add an event listener to the submit button
        submitButton.addEventListener("click", function() {
            // Manually trigger the form submission
            this.form.submit();
        });
    
        function insertPageLink() {
        const editor = simplemde.codemirror;
        const selectedText = editor.getSelection();
        const linkFile = prompt("Enter the link filename:");
        const linkTitle = prompt("Enter the link title:");
        
        if (linkTitle !== null) {
            if (linkTitle == ''){
                const linkText = `[${linkFile}]`;
            }
            else{
                const linkText = `[${linkFile}|${linkTitle}]`;
            }
            editor.replaceSelection(linkText);
        }
    }

    const simplemde = new SimpleMDE({
        element: document.getElementById("content"),
        toolbar: [
            "bold", "italic", "heading", "quote", "unordered-list", "ordered-list",
            "|", "link", "image", "table", "horizontal-rule", "code", "preview",
            {
                name: "insert-page-link",
                action: insertPageLink,
                className: "fa fa-external-link",
                title: "Insert Page Link"
            }
        ]
    });
    </script>

    <script>
    $('input[name=tags]').tagify();
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Wiki App{% endblock %}

{% block content %}
    <h1>Welcome to the Wiki App</h1>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}
    <form method="POST" action="{{ url_for('auth.login') }}">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
        <br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <br>
        <button type="submit">Login</button>
    </form>
    <p>Don't have an account? <a href="{{ url_for('auth.register') }}">Register</a></p>
{% endblock %}

templates/manage_articles.html
{% extends 'base.html' %}

{% block title %}
    Manage Articles
{% endblock %}

{% block content %}
    <h1>Manage Articles</h1>
    
    <form action="{{ url_for('articles.perform_bulk_action') }}" method="post" class="mb-3">
        <div class="form-group">
            <label for="bulk-action">Bulk Action:</label>
            <select name="bulk_action" id="bulk-action" class="form-control">
                <option value="delete">Delete Selected</option>
                <!-- Add other bulk actions as needed -->
            </select>
        </div>
        <button type="submit" class="btn btn-danger">Apply</button>
    </form>
    
    {% if pagination.total == 0 %}
        <p>No articles found.</p>
    {% else %}
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr>
                    <th></th>
                    <th>Article Title</th>
                    <th>Tags</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for article in articles %}
                    <tr>
                        <td><input type="checkbox" name="selected_articles" value="{{ article.filename }}"></td>
                        <td style="width: auto">
                            {% if article.filename.startswith('_sp_') %}
                                <span class="btn btn-warning btn-sm p-1">Special</span>
                            {% endif %}
                            {% if article.filename.startswith('_bl_') %}
                                <span class="btn btn-success btn-sm p-1">Block</span>
                            {% endif %}
                            <a href="{{ url_for('articles.view_article', filename=article.filename) }}">{{ article.title }}</a>
                        </td>
                        <td>
                            {% for tag in article.tags %}
                                {% if tag != "" %}
                                    <a href="{{ url_for('articles.tagged_articles', tag=tag) }}"  class="btn btn-info btn-sm p-1">{{ tag }}</a>
                                {% endif %}
                            {% endfor %}
                        </td>
                        <td>
                            <a href="{{ url_for('articles.confirm_delete', filename=article.filename) }}" class="btn btn-danger btn-sm">Remove</a>
                            <a href="{{ url_for('articles.edit_article', filename=article.filename) }}" class="btn btn-info btn-sm">Edit</a>
                            <a href="{{ url_for('articles.view_article_versions', filename=article.filename) }}" class="btn btn-secondary btn-sm">Show All Versions</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        
        <!-- Pagination -->
        <div class="pagination">
            {{ pagination.info }}
            {{ pagination.links }}
        </div>
    {% endif %}
    
    <a href="{{ url_for('articles.index') }}" class="btn btn-primary mt-3">Back to Home</a>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block content %}
    <h2>Register</h2>
    <form method="POST" action="{{ url_for('auth.register') }}">
        <div class="form-group">
            <label for="username">Username:</label>
            <input type="text" id="username" name="username" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="password">Password:</label>
            <input type="password" id="password" name="password" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
    <p>Already have an account? <a href="{{ url_for('auth.login') }}">Login</a></p>
{% endblock %}

templates/search_results.html
{% block title %}
    Search Results for "{{ query }}"
{% endblock %}

{% block content %}
    <div class='markdown-body'><h2>Search Results for "{{ query }}"</h2></div>

    {% if results %}
        <div class="list-group">
            {% for result in results %}
                <a href="{{ url_for('articles.view_article', filename=result.filename) }}" class="list-group-item list-group-item-action">
                    <h4 class="mb-1">{{ result.title }}</h4>
                    <p class="mb-1">{{ result.highlighted_content|safe }}</p>
                </a>
            {% endfor %}
        </div>
    {% else %}
        <p class="no-results">No results found for "{{ query }}".</p>
    {% endif %}

    {% if pagination.pages|length > 1 %}
        <div class="pagination mt-3">
            <span class="mr-2">Page {{ pagination.page }} of {{ pagination.pages|length }}</span>
            {% if pagination.has_prev %}
                <a href="{{ pagination.prev() }}">Previous</a>
            {% endif %}
            {% for page in pagination.pages %}
                {% if pagination.page == page %}
                    <span class="current">{{ page }}</span>
                {% else %}
                    <a href="{{ pagination.href(page) }}">{{ page }}</a>
                {% endif %}
            {% endfor %}
            {% if pagination.has_next %}
                <a href="{{ pagination.next() }}">Next</a>
            {% endif %}
        </div>
    {% endif %}
    
    <a href="{{ url_for('articles.index') }}" class="btn btn-primary mt-3">Back to Home</a>
{% endblock %}

templates/special_page.html
{% extends 'base.html' %}

{% block title %}
    {{ article.versions[-1].title }}
{% endblock %}

{% block content %}
    <div class='markdown-body'><h1><strong>{{ article.versions[-1].title }}</strong></h1></div>
    
    <div class="article-content markdown-body">
        {{ article.versions[-1].content|markdown_to_html|link_articles|safe }}
    </div>
    <br />
    <span class="alert alert-light fnt-10">
        <div class="float_right">
            <a href="{{ url_for('articles.view_article_versions', filename=article.filename) }}" class="badge badge-light">View Versions</a>
            <a href="{{ url_for('articles.edit_article', filename=article.filename) }}" class="badge badge-light">Edit Article</a>
        </div>
        <em>Last change: {{ article.versions[-1].timestamp | format_timestamp }}</em></span><br style="clear: both" />  
  
    {% endblock %}

templates/tagged_articles.html
{% extends 'base.html' %}

{% block title %}
    Articles Tagged "{{ tag }}"
{% endblock %}

{% block content %}
<div class='markdown-body'><h2>#{{ tag }}</h2></div>
    <br />
    {% if articles %}
        <div class="list-group">
            {% for article in articles %}
                <a href="{{ url_for('articles.view_article', filename=article.filename) }}" class="btn-secondary list-group-item list-group-item-action">
                    <h4 class="mb-1">{{ article.title }}</h4>
                    <p class="mb-1">{{ article.content|safe }}</p>
                </a>
            {% endfor %}
        </div>

        <div class="pagination mt-4">
            {% if pagination.has_pages %}
                {{ pagination.info }}
                {{ pagination.links }}
            {% endif %}
        </div>
    {% else %}
        <p class="no-results">No articles found for tag "{{ tag }}".</p>
    {% endif %}

    <a href="{{ url_for('articles.index') }}" class="btn btn-primary mt-3">Back to Home</a>
{% endblock %}

templates/view_specific_version.html
{% extends 'base.html' %}

{% block title %}
    {{ article_data.versions[-1].title }} - {{ version.title }} (Version)
{% endblock %}

{% block content %}
    <a href="{{ url_for('articles.view_article_versions', filename=article_data.filename) }}" class="float-right btn btn-primary ">Back to Versions</a>
    <h3>{{ version.title }} (Version)</h3>
    <p>Timestamp: {{ version.timestamp }}</p>
    <br />
    <div class="article-content markdown-body">
        {{ version.content|markdown_to_html|link_articles|safe }}
    </div>
{% endblock %}